# Generated by Django 4.0.2 on 2022-02-13 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point', '0008_cartcarbon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbonpoint', models.IntegerField()),
                ('greenpoint', models.IntegerField()),
                ('vehiclepoint', models.IntegerField()),
                ('totalpoint', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '탄소포인트 장바구니',
            },
        ),
        migrations.RemoveField(
            model_name='cartcarbon',
            name='carbonpoint',
        ),
        migrations.RemoveField(
            model_name='cartcarbon',
            name='user',
        ),
        migrations.DeleteModel(
            name='Carbon',
        ),
        migrations.DeleteModel(
            name='Cartcarbon',
        ),
    ]
