# Generated by Django 4.0.2 on 2022-02-14 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point', '0009_userpoint_remove_cartcarbon_carbonpoint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpoint',
            old_name='vehiclepoint',
            new_name='carpoint',
        ),
        migrations.CreateModel(
            name='Carpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpoint', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '자동차탄소포인트',
                'db_table': 'Carpoint',
            },
        ),
    ]
