# Generated by Django 4.0.2 on 2022-02-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0010_remove_userpoint_modify_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='carbonpoint',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='greenpoint',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='totalpoint',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='vehiclepoint',
            field=models.IntegerField(blank=True),
        ),
    ]
