# Generated by Django 4.0.2 on 2022-02-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0010_rename_vehiclepoint_userpoint_carpoint_carpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoint',
            name='carpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
