# Generated by Django 4.0.2 on 2022-02-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0011_alter_userpoint_carbonpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='carbonpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='greenpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='totalpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='vehiclepoint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
