# Generated by Django 4.0.2 on 2022-02-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0011_alter_carpoint_carpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpoint',
            name='carpoint',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='carbonpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='carpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='greenpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='totalpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
