# Generated by Django 4.0.2 on 2022-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0012_alter_userpoint_carbonpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='carbonpoint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
