# Generated by Django 4.0.2 on 2022-02-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0013_alter_userpoint_carbonpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='carbonpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
