# Generated by Django 4.0.2 on 2022-02-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0014_alter_userpoint_carbonpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenpoint',
            name='gpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
