# Generated by Django 4.0.2 on 2022-02-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0014_alter_userpoint_carbonpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoint',
            name='carbonpoint',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='greenpoint',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='totalpoint',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userpoint',
            name='vehiclepoint',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
