# Generated by Django 4.0.2 on 2022-02-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0016_alter_carbonpoint_cpoint_alter_greenpoint_gpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonpoint',
            name='cpoint',
            field=models.IntegerField(),
        ),
    ]
